config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "search#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "chef#index"
  get "/about", to:"about#index"
  get 'chef/index', to: "chef#index"
  get 'chef/:id', to: "chef#show", as: 'chef'
  get 'restaurant/index', to:"restaurant#index"
  get 'restaurant/:id', to:"restaurant#show", as: 'restaurant'
  get 'meal/index', to:"meal#index"
  get 'meal/:id', to:"meal#show", as: 'meal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
    validates :ChefName, presence: true
    validates :ChefAge, numericality: true

    paginates_per 30

    belongs_to :restaurant
end

app/models/meal.rb
class Meal < ApplicationRecord
    validates :MealName, length: {minimum: 2}
    validates :MealName, presence: true

    paginates_per 30

    belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :LocationLatitude, :LocationLongitude, presence: true
    validates :LocationLatitude, :LocationLongitude, numericality: true

    paginates_per 30

    has_many :chefs
    has_many :meals
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_dropdown_options

    def set_dropdown_options
        @cuisines = Restaurant.pluck(:Cuisine).uniq
    end
end

app/controllers/chef_controller.rb
class ChefController < ApplicationController
  def index
    @chefs = Chef.page(params[:page])
  end

  def show
    @chef = Chef.find(params[:id])
  end
end

app/controllers/meal_controller.rb
class MealController < ApplicationController
  def index
    @meals = Meal.page(params[:page])
  end

  def show
    @meal = Meal.find(params[:id])
  end
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
  def index
    @restaurants = Restaurant.order(:Cuisine).page(params[:page])
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @searchterm = params[:query]
    @choosencuisine = params[:cuisine]

    if params[:cuisine] == "All"
      @restaurants = Restaurant.where("LOWER(RestaurantName) LIKE LOWER(?)", "%#{Restaurant.sanitize_sql_like(params[:query])}%")
      @count = @restaurants.count
      @restaurants = @restaurants.page(params[:page])
    else
      @restaurants = Restaurant.where("LOWER(RestaurantName) LIKE LOWER(?) AND LOWER(Cuisine) = LOWER(?)", "%#{Restaurant.sanitize_sql_like(params[:query])}%", params[:cuisine])
      @count = @restaurants.count
    end
    @restaurants = @restaurants.page(params[:page])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chef_helper.rb
module ChefHelper
end

app/helpers/meal_helper.rb
module MealHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/about/index.html.erb
<div class="container has-text-centered">
    <h1 class="title is-1">About</h1>
</div>

<h4 class="subtitle is-3">Chef Registry Datasources</h4>

<div class="content">

    <p>This project is a registry on restaurants and their chefs. A collection of
    meals prepared at the various restaurants is also listed. There will be 3 tables: Chefs,Restaurants and Meals.
    </p>

    <h2>Chef</h2>

        <p>For the Chef's name, age and nationality I used the <strong>Faker Gem</strong><sup><a href="https://github.com/faker-ruby/faker">[1]</a></sup> to generate the data dynamically.
         The Chefs table will store name, age, and nationality of the chefs. This information is generated by the Faker gem. The Faker generators used is:
        </p>

        <ul>
            <li>Faker::Name.name</li>
            <li>Faker::Nation.nationality</li>
            <li>Faker::Number.between(from: 21, to: 65)</li>
        </ul>

        <p>The Datatype of the fields in the Chef's table are:</p>

        <table>
            <thead>
                <tr>
                    <td>Column Name</td>
                <td>Data Type</td>
                <td>Description</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>ChefID</td>
                    <td>integer</td>
                    <td>Primary Key of the Chef record</td>
                </tr>
                <tr>
                    <td>ChefName</td>
                    <td>string</td>
                    <td>Chef's Name</td>
                </tr>
                <tr>
                    <td>ChefAge</td>
                    <td>string</td>
                    <td>Age of Chef</td>
                </tr>
            </tbody>
        </table>

    <h2>Restaurant</h2>

        <p>The restaurant data was sourced from the <strong>Dinesafe</strong> open dataset<sup><a href="https://open.toronto.ca/dataset/dinesafe/">[2]</a></sup>. Dinesafe is a food safety program that inspects all establishments serving food. I extracted the Name of the restaurant and the location coordinates for the map.

            The API provided has a link to a downloadable CSV file which was stored in the project's db folder. In the db/seed.rb file, the data is read from the file, but only the mentioned columns were taken. It was also filtered by the "Establishment Type" to retrieve strickly restaurants.
        </p>

        <p>
            The Restaurant’s table will the restaurant’s name, cuisine, latitude and longitude. The cuisine field will be generated from the Faker::Food.ethinic_category.
        </p>

        <p>The Datatype of the fields in the restaurant's table are:</p>

        <table>
            <thead>
                <tr>
                    <td>Column Name</td>
                    <td>Data Type</td>
                    <td>Description</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>RestaurantID</td>
                    <td>integer</td>
                    <td>Primary Key of the restaurant</td>
                </tr>
                <tr>
                    <td>RestaurantName</td>
                    <td>string</td>
                    <td>Restaurant's Name</td>
                </tr>
                <tr>
                    <td>LocationLatitude</td>
                    <td>string</td>
                    <td>Restaurant’s Location Latitude</td>
                </tr>
                <tr>
                    <td>LocationLongitude</td>
                    <td>string</td>
                    <td>Restaurant’s Location longitude</td>
                </tr>
                <tr>
                    <td>Cuisine</td>
                    <td>string</td>
                    <td>Restaurant's style</td>
                </tr>
            </tbody>
        </table>

    <h2>Meal</h2>

        <p>The meal data came from the free API provided by <strong>TheMealDB</strong><sup><a href="https://www.themealdb.com/api.php">[3]</a></sup>. None of the APIs provided a way to directly access <strong>all</strong> meals in all <strong>categories</strong>. So a script was written to read all the meals for each category and then store the results in a csv file. The csv file was then imported into the db folder to be read in the db/seed.rb file.</p>

        <p>The meal's table will be structure:</p>

        <table>
            <thead>
                <tr>
                    <td>Column Name</td>
                    <td>Data Type</td>
                    <td>Description</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>MealID</td>
                    <td>integer</td>
                    <td>Primary Key of the meal record</td>
                </tr>
                <tr>
                    <td>MealName</td>
                    <td>string</td>
                    <td>Name of meal</td>
                </tr>
                <tr>
                    <td>Image</td>
                    <td>string</td>
                    <td>Url of meal image</td>
                </tr>
            </tbody>
        </table>

</div>

app/views/chef/index.html.erb
<div class="container has-text-centered">
    <h1 class="title is-1">List Of Chefs</h1>
</div>

<div class="is-flex is-justify-content-flex-end">
    <%= paginate @chefs %>
</div>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Chef Name</th>
                <th>Chef Age</th>
                <th>Nationality</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @chefs.each do |chef|%>
            <tr>
                <td>
                    <%= chef.ChefName%>
                </td>
                <td>
                    <%= chef.ChefAge%>
                </td>
                <td>
                    <%= chef.Nationality%>
                </td>
                <td>
                    <%= link_to 'View', chef_path(chef), class: "button is-link" %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/chef/show.html.erb
<h1 class="title is-1">Chef <%= @chef.ChefName %></h1>

<div class="columns">
    <div class="column">
    <h3 class="title is-4">Age: <%= @chef.ChefAge%> years</h3>
    <h5 class="title is-5">Nationality: <%= @chef.Nationality%></h5>
    <p> Works at: <%= link_to @chef.restaurant.RestaurantName, restaurant_path(@chef.restaurant)%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRailsProj</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/menu" %>
    <section class="section container">
      <%= yield %>
    </section>
  </body>
</html>

app/views/meal/index.html.erb
<div class="container has-text-centered">
    <h1 class="title is-1">List Of Meals</h1>
</div>

<div class="is-flex is-justify-content-flex-end">
    <%= paginate @meals %>
</div>

<div class="container">
    <table class="table">
    <thead>
        <tr>
            <th>Name of Meal</th>
            <th>Restaurant</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @meals.each do |meal|%>
        <tr>
            <td>
                <%= meal.MealName%>
            </td>
            <td>
                <%= link_to meal.restaurant.RestaurantName, restaurant_path(meal.restaurant) %>
            </td>
            <td>
                <%= link_to 'View', meal_path(meal), class: "button is-link" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/meal/show.html.erb
<h1 class="title is-1"><%= @meal.MealName%></h1>

<div class="columns">
    <div class="column">
    <h5 class="title is-5">Served At: <%= link_to @meal.restaurant.RestaurantName, restaurant_path(@meal.restaurant) %></h5>

    <div class="tile is-parent is-8">
      <article class="tile is-child notification is-info">
        <p class="title">Delicious <%= @meal.MealName %> Image:</p>
        <figure class="image is-2by3">
            <img src="<%= @meal.Image %>" alt="<%= @meal.MealName %>">
        </figure>
      </article>
    </div>
    </div>
</div>

app/views/restaurant/index.html.erb
<div class="container has-text-centered">
    <h1 class="title is-1">List Of Restaurants</h1>
</div>

<div class="is-flex is-justify-content-flex-end">
    <%= paginate @restaurants %>
</div>

<div class="container">
<table class="table">
    <thead>
        <tr>
            <th>Restaurant Name</th>
            <th>Cusine</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @restaurants.each do |res|%>
        <tr>
            <td>
                <%= res.RestaurantName%>
            </td>
            <td>
                <%= res.Cuisine %>
            </td>
            <td>
                <%= link_to 'View', restaurant_path(res), class: "button is-link" %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/restaurant/show.html.erb
<h1 class="title is-1"><%= @restaurant.RestaurantName%></h1>


<div class="columns">
    <div class="column">
    <h3 class="title is-4">Cuisine: <%= @restaurant.Cuisine%></h3>
    <span class="title">Chefs featured:</span>
    <% if @restaurant.chefs.count == 0 %>
        <ul>
            <li class="pl-4">No Chefs currently</li>
        </ul>
    <% else %>
        <ul>
            <% @restaurant.chefs.each do |chef| %>
            <li class="pl-4"><%= link_to chef.ChefName, chef_path(chef) %></li>
            <% end %>
        </ul>
    <% end %>
    <br>
    <span class="title">Meals served:</span>
    <% if @restaurant.meals.count == 0 %>
        <ul>
            <li class="pl-4">No Meals currently</li>
        </ul>
    <% else %>
        <ul>
            <% @restaurant.meals.each do |meal| %>
            <li class="pl-4"><%= link_to meal.MealName, meal_path(meal) %></li>
            <% end %>
        </ul>
    <% end %>
    </div>
    <div class="column">
        <div class="title is-parent is-8">
        <article class="tile is-child notification is-info">
            <p class="title">Located:</p>
                <figure class="image">
                    <img src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @restaurant.LocationLatitude%>,<%= @restaurant.LocationLongitude%>&zoom=14&size=400x400&markers=color:red%7Clabel:C%7C<%=@restaurant.LocationLatitude%>,<%=@restaurant.LocationLongitude%>&key=<%= ENV['API_KEY']%>" alt="Location" />

                </figure>
        </article>
        </div>
    </div>
</div>

app/views/search/index.html.erb
<h1 class="title is-1">Search Results</h1>

<div class="container">
<p> Your search for "<%= @searchterm %>" in <%= @choosencuisine %> found <%= @count %> results</p>
<div class="is-flex is-justify-content-flex-end">
    <%= paginate @restaurants %>
</div>
        <ul class="pl-3">
           <% @restaurants.each do |res|%>
                <li>
                <%= link_to res.RestaurantName, restaurant_path(res) %>
                </li>
           <% end %>
        </ul>
</div>

app/views/shared/_menu.html.erb
<nav class="navbar is-link is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item is-uppercase has-text-weight-bold" href="/">
        CHEF REGISTRY
        </a>
         <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="restuarantmenuitem">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>

    </div>

    <div id="restuarantmenuitem" class="navbar-menu">
        <div class="navbar-start">

            <%= link_to "Restaurants", restaurant_index_path, class: "navbar-item" %>
            <%= link_to "Chefs", chef_index_path, class: "navbar-item" %>
            <%= link_to "Meals", meal_index_path, class: "navbar-item" %>
            <%= link_to "About", about_path, class: "navbar-item" %>

        </div>
        <div class="navbar-end">
            <div class="navbar-item is-flex">
                <%= form_with url: "/search", method: :get do |form| %>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= form.label :query, "Search for:" %>
                        </div>
                        <div class="control">
                            <%= form.text_field :query, class: "input is-link is-small" %>
                        </div>
                        <div class="control is-align-items-stretch">
                            <%= form.select :cuisine, options_for_select(["All"] + @cuisines) %>
                        </div>
                        <div class="control">
                            <%= form.submit "Search",class: "button is-dark is-small" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>



</nav>